### ISSUE TITLE
UTC timestamps in Opta F7 no present before 08.05.2022

### ISSUE THREAD

**Issue by rdghe** [Alek050/databallpy#93]
Currently, databallpy uses the following attributes from the `Stat` element of the Opta F7 XML:
- `first_half_start_utc`
- `first_half_stop_utc`
- `second_half_start_utc`
- `second_half_stop_utc`

From what I could find, these fields only exist for matches more recent than the 8th of May 2022.

I recommend using the non `utc` counterparts instead, as those exist in ALL datasets.

Moreover, the error thrown when these fields do not exist is not handled correctly.

-----------------------------------------------------------------

The same thing is valid for the `timestamp_utc` attribute of the `Event` element from the Opta F24 XML.

**Comment by Alek050** [comment]
Hi @rdghe and @DaanGro,

First of all thanks for looking into this and sorry I could not respond earlier, but I think something went wrong in the solution. As far as I can see the proposed solution code ignores time zones.

For the match on 2023-01-22 (winter time) everything is fine:
`<Stat Type="first_half_start">20230122T133209+0000</Stat>`
`<Stat Type="first_half_start_utc">20230122T133209+0000</Stat>`

For the match on 2023-04-07 (summer time) there is an hour difference:
`<Stat Type="first_half_start">20230407T190136+0100</Stat>`
`<Stat Type="first_half_start_utc">20230407T180136+0000</Stat>`

simply parsing the date with `utc=True` will result in wrong times. I think what is happening here is that times (without `_utc`) are localized to the headquarters of opta in England. UTC does not change with regard to summer and winter times, and is equal to the English time zone in the winter, but since the English timezone does change with regard to winter and summer times, in the summer UTC and English time are not equal.

I propose to use `.dt.localize("Europe/London")`, and then later changing it to dutch timezone.

**Comment by rdghe** [comment]
@Alek050 I am not sure that I get your concern, the two datetime strings are parsed into equivalent datetime objects when using `pd.to_datetime()` with `utc=True`. To test that you can run the following example:
```
import pandas as pd

datetime_string_non_utc = '20230407T190136+0100'
datetime_string_utc = '20230407T180136+0000'

datetime_non_utc = pd.to_datetime(datetime_string_non_utc, utc=True)
datetime_utc = pd.to_datetime(datetime_string_utc, utc=True)

datetime_non_utc == datetime_utc
```
You will see that the output of the last statement is `True`, as both datetimes resolve to `Timestamp('2023-04-07 18:01:36+0000', tz='UTC')`.

**Comment by Alek050** [comment]
Aah thats right, the `+0100` already indicates the timezone of course. Thanks for the explanation.
